/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

function Narokan(props) {
  const { nodes, materials } = useGLTF("/models/Narokan_001.glb");
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="Case"
          castShadow
          receiveShadow
          geometry={nodes.Case.geometry}
          material={materials["Material.002"]}
          position={[-0.001, 0.619, 0]}
        />
        <mesh
          name="Cylinder"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder.geometry}
          material={materials["Material.002"]}
          position={[-0.007, 0.89, 0.194]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.474, 0.104, 0.474]}
        />
        <mesh
          name="Lamp-cover"
          castShadow
          receiveShadow
          geometry={nodes["Lamp-cover"].geometry}
          material={materials["Material.001"]}
          position={[-0.007, 0.89, 0.165]}
          rotation={[Math.PI / 2, 0.197, 0]}
          scale={0.458}
        />
        <mesh
          name="screw_l"
          castShadow
          receiveShadow
          geometry={nodes.screw_l.geometry}
          material={materials.Material}
          position={[-0.409, 0.898, 0.449]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.038}
        />
        <mesh
          name="screw_l009"
          castShadow
          receiveShadow
          geometry={nodes.screw_l009.geometry}
          material={materials.Material}
          position={[0.404, 0.898, 0.449]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.038}
        />
        <mesh
          name="Green"
          castShadow
          receiveShadow
          geometry={nodes.Green.geometry}
          material={materials["Material.004"]}
          position={[0.004, 1.104, 0.368]}
          rotation={[Math.PI / 2, Math.PI / 4, 0]}
          scale={0.144}
        />
        <mesh
          name="Red"
          castShadow
          receiveShadow
          geometry={nodes.Red.geometry}
          material={materials["Material.003"]}
          position={[-0.221, 0.879, 0.368]}
          rotation={[Math.PI / 2, Math.PI / 4, 0]}
          scale={0.144}
        />
        <mesh
          name="Yellow"
          castShadow
          receiveShadow
          geometry={nodes.Yellow.geometry}
          material={materials["Material.005"]}
          position={[0.006, 0.663, 0.368]}
          rotation={[Math.PI / 2, Math.PI / 4, 0]}
          scale={0.144}
        />
        <mesh
          name="Blue"
          castShadow
          receiveShadow
          geometry={nodes.Blue.geometry}
          material={materials["Material.006"]}
          position={[0.225, 0.883, 0.368]}
          rotation={[Math.PI / 2, Math.PI / 4, 0]}
          scale={0.144}
        />
        <mesh
          name="Cylinder001"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001.geometry}
          material={materials["Material.002"]}
          position={[0.947, 0.89, 0.194]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.474, 0.104, 0.474]}
        />
        <mesh
          name="Lamp-cover001"
          castShadow
          receiveShadow
          geometry={nodes["Lamp-cover001"].geometry}
          material={materials["Material.001"]}
          position={[0.947, 0.89, 0.165]}
          rotation={[Math.PI / 2, 0.198, 0]}
          scale={0.458}
        />
        <mesh
          name="screw_l001"
          castShadow
          receiveShadow
          geometry={nodes.screw_l001.geometry}
          material={materials.Material}
          position={[0.548, 0.888, 0.449]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.038}
        />
        <mesh
          name="screw_r001"
          castShadow
          receiveShadow
          geometry={nodes.screw_r001.geometry}
          material={materials.Material}
          position={[1.353, 0.898, 0.449]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.038}
        />
        <mesh
          name="Blue001"
          castShadow
          receiveShadow
          geometry={nodes.Blue001.geometry}
          material={materials["Material.006"]}
          position={[1.174, 0.883, 0.368]}
          rotation={[Math.PI / 2, Math.PI / 4, 0]}
          scale={0.144}
        />
        <mesh
          name="Green001"
          castShadow
          receiveShadow
          geometry={nodes.Green001.geometry}
          material={materials["Material.004"]}
          position={[0.953, 1.104, 0.368]}
          rotation={[Math.PI / 2, Math.PI / 4, 0]}
          scale={0.144}
        />
        <mesh
          name="Red001"
          castShadow
          receiveShadow
          geometry={nodes.Red001.geometry}
          material={materials["Material.003"]}
          position={[0.728, 0.879, 0.368]}
          rotation={[Math.PI / 2, Math.PI / 4, 0]}
          scale={0.144}
        />
        <mesh
          name="Yellow001"
          castShadow
          receiveShadow
          geometry={nodes.Yellow001.geometry}
          material={materials["Material.005"]}
          position={[0.955, 0.663, 0.368]}
          rotation={[Math.PI / 2, Math.PI / 4, 0]}
          scale={0.144}
        />
        <mesh
          name="Cylinder002"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder002.geometry}
          material={materials["Material.002"]}
          position={[1.902, 0.89, 0.194]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.474, 0.104, 0.474]}
        />
        <mesh
          name="Lamp-cover002"
          castShadow
          receiveShadow
          geometry={nodes["Lamp-cover002"].geometry}
          material={materials["Material.001"]}
          position={[1.902, 0.89, 0.165]}
          rotation={[Math.PI / 2, 0.211, 0]}
          scale={0.458}
        />
        <mesh
          name="screw_r002"
          castShadow
          receiveShadow
          geometry={nodes.screw_r002.geometry}
          material={materials.Material}
          position={[2.308, 0.898, 0.449]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.038}
        />
        <mesh
          name="screw_l002"
          castShadow
          receiveShadow
          geometry={nodes.screw_l002.geometry}
          material={materials.Material}
          position={[1.501, 0.887, 0.449]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.038}
        />
        <mesh
          name="Blue002"
          castShadow
          receiveShadow
          geometry={nodes.Blue002.geometry}
          material={materials["Material.007"]}
          position={[2.139, 0.883, 0.368]}
          rotation={[Math.PI / 2, Math.PI / 4, 0]}
          scale={0.144}
        />
        <mesh
          name="Green002"
          castShadow
          receiveShadow
          geometry={nodes.Green002.geometry}
          material={materials["Material.009"]}
          position={[1.918, 1.104, 0.368]}
          rotation={[Math.PI / 2, Math.PI / 4, 0]}
          scale={0.144}
        />
        <mesh
          name="Red002"
          castShadow
          receiveShadow
          geometry={nodes.Red002.geometry}
          material={materials["Material.010"]}
          position={[1.693, 0.879, 0.368]}
          rotation={[Math.PI / 2, Math.PI / 4, 0]}
          scale={0.144}
        />
        <mesh
          name="Yellow002"
          castShadow
          receiveShadow
          geometry={nodes.Yellow002.geometry}
          material={materials["Material.008"]}
          position={[1.92, 0.663, 0.368]}
          rotation={[Math.PI / 2, Math.PI / 4, 0]}
          scale={0.144}
        />
        <mesh
          name="Cylinder003"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder003.geometry}
          material={materials["Material.002"]}
          position={[0.473, 0.081, 0.194]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.474, 0.104, 0.474]}
        />
        <mesh
          name="Lamp-cover003"
          castShadow
          receiveShadow
          geometry={nodes["Lamp-cover003"].geometry}
          material={materials["Material.001"]}
          position={[0.473, 0.081, 0.165]}
          rotation={[Math.PI / 2, 0.196, 0]}
          scale={0.458}
        />
        <mesh
          name="screw_r003"
          castShadow
          receiveShadow
          geometry={nodes.screw_r003.geometry}
          material={materials.Material}
          position={[0.88, 0.081, 0.449]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.038}
        />
        <mesh
          name="screw_l003"
          castShadow
          receiveShadow
          geometry={nodes.screw_l003.geometry}
          material={materials.Material}
          position={[0.074, 0.083, 0.449]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.038}
        />
        <mesh
          name="Blue003"
          castShadow
          receiveShadow
          geometry={nodes.Blue003.geometry}
          material={materials["Material.014"]}
          position={[0.693, 0.068, 0.368]}
          rotation={[Math.PI / 2, Math.PI / 4, 0]}
          scale={0.144}
        />
        <mesh
          name="Green003"
          castShadow
          receiveShadow
          geometry={nodes.Green003.geometry}
          material={materials["Material.012"]}
          position={[0.472, 0.29, 0.368]}
          rotation={[Math.PI / 2, Math.PI / 4, 0]}
          scale={0.144}
        />
        <mesh
          name="Red003"
          castShadow
          receiveShadow
          geometry={nodes.Red003.geometry}
          material={materials["Material.011"]}
          position={[0.247, 0.065, 0.368]}
          rotation={[Math.PI / 2, Math.PI / 4, 0]}
          scale={0.144}
        />
        <mesh
          name="Yellow003"
          castShadow
          receiveShadow
          geometry={nodes.Yellow003.geometry}
          material={materials["Material.013"]}
          position={[0.473, -0.151, 0.368]}
          rotation={[Math.PI / 2, Math.PI / 4, 0]}
          scale={0.144}
        />
        <mesh
          name="Cylinder004"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder004.geometry}
          material={materials["Material.002"]}
          position={[0.934, -0.745, 0.194]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.474, 0.104, 0.474]}
        />
        <mesh
          name="Lamp-cover004"
          castShadow
          receiveShadow
          geometry={nodes["Lamp-cover004"].geometry}
          material={materials["Material.001"]}
          position={[0.934, -0.745, 0.165]}
          rotation={[Math.PI / 2, 0.224, 0]}
          scale={0.458}
        />
        <mesh
          name="screw_r004"
          castShadow
          receiveShadow
          geometry={nodes.screw_r004.geometry}
          material={materials.Material}
          position={[1.34, -0.742, 0.449]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.038}
        />
        <mesh
          name="screw_l004"
          castShadow
          receiveShadow
          geometry={nodes.screw_l004.geometry}
          material={materials.Material}
          position={[0.539, -0.752, 0.449]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.038}
        />
        <mesh
          name="Blue004"
          castShadow
          receiveShadow
          geometry={nodes.Blue004.geometry}
          material={materials["Material.015"]}
          position={[1.165, -0.739, 0.368]}
          rotation={[Math.PI / 2, Math.PI / 4, 0]}
          scale={0.144}
        />
        <mesh
          name="Green004"
          castShadow
          receiveShadow
          geometry={nodes.Green004.geometry}
          material={materials["Material.017"]}
          position={[0.944, -0.517, 0.368]}
          rotation={[Math.PI / 2, Math.PI / 4, 0]}
          scale={0.144}
        />
        <mesh
          name="Red004"
          castShadow
          receiveShadow
          geometry={nodes.Red004.geometry}
          material={materials["Material.018"]}
          position={[0.719, -0.742, 0.368]}
          rotation={[Math.PI / 2, Math.PI / 4, 0]}
          scale={0.144}
        />
        <mesh
          name="Yellow004"
          castShadow
          receiveShadow
          geometry={nodes.Yellow004.geometry}
          material={materials["Material.016"]}
          position={[0.946, -0.958, 0.368]}
          rotation={[Math.PI / 2, Math.PI / 4, 0]}
          scale={0.144}
        />
        <mesh
          name="Cylinder005"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder005.geometry}
          material={materials["Material.002"]}
          position={[-0.956, -0.745, 0.194]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.474, 0.104, 0.474]}
        />
        <mesh
          name="Lamp-cover005"
          castShadow
          receiveShadow
          geometry={nodes["Lamp-cover005"].geometry}
          material={materials["Material.001"]}
          position={[-0.956, -0.745, 0.165]}
          rotation={[Math.PI / 2, 0.248, 0]}
          scale={0.458}
        />
        <mesh
          name="screw_r005"
          castShadow
          receiveShadow
          geometry={nodes.screw_r005.geometry}
          material={materials.Material}
          position={[-0.559, -0.723, 0.449]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.038}
        />
        <mesh
          name="screw_l005"
          castShadow
          receiveShadow
          geometry={nodes.screw_l005.geometry}
          material={materials.Material}
          position={[-1.351, -0.769, 0.449]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.038}
        />
        <mesh
          name="Blue005"
          castShadow
          receiveShadow
          geometry={nodes.Blue005.geometry}
          material={materials["Material.022"]}
          position={[-0.732, -0.753, 0.368]}
          rotation={[Math.PI / 2, Math.PI / 4, 0]}
          scale={0.144}
        />
        <mesh
          name="Green005"
          castShadow
          receiveShadow
          geometry={nodes.Green005.geometry}
          material={materials["Material.020"]}
          position={[-0.954, -0.532, 0.368]}
          rotation={[Math.PI / 2, Math.PI / 4, 0]}
          scale={0.144}
        />
        <mesh
          name="Red005"
          castShadow
          receiveShadow
          geometry={nodes.Red005.geometry}
          material={materials["Material.019"]}
          position={[-1.178, -0.757, 0.368]}
          rotation={[Math.PI / 2, Math.PI / 4, 0]}
          scale={0.144}
        />
        <mesh
          name="Yellow005"
          castShadow
          receiveShadow
          geometry={nodes.Yellow005.geometry}
          material={materials["Material.021"]}
          position={[-0.952, -0.972, 0.368]}
          rotation={[Math.PI / 2, Math.PI / 4, 0]}
          scale={0.144}
        />
        <mesh
          name="Cylinder006"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder006.geometry}
          material={materials["Material.002"]}
          position={[-0.495, 0.081, 0.194]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.474, 0.104, 0.474]}
        />
        <mesh
          name="Lamp-cover006"
          castShadow
          receiveShadow
          geometry={nodes["Lamp-cover006"].geometry}
          material={materials["Material.001"]}
          position={[-0.495, 0.081, 0.165]}
          rotation={[Math.PI / 2, 0.206, 0]}
          scale={0.458}
        />
        <mesh
          name="screw_r006"
          castShadow
          receiveShadow
          geometry={nodes.screw_r006.geometry}
          material={materials.Material}
          position={[-0.092, 0.084, 0.449]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.038}
        />
        <mesh
          name="screw_l006"
          castShadow
          receiveShadow
          geometry={nodes.screw_l006.geometry}
          material={materials.Material}
          position={[-0.887, 0.077, 0.449]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.038}
        />
        <mesh
          name="Blue006"
          castShadow
          receiveShadow
          geometry={nodes.Blue006.geometry}
          material={materials["Material.023"]}
          position={[-0.274, 0.068, 0.368]}
          rotation={[Math.PI / 2, Math.PI / 4, 0]}
          scale={0.144}
        />
        <mesh
          name="Green006"
          castShadow
          receiveShadow
          geometry={nodes.Green006.geometry}
          material={materials["Material.025"]}
          position={[-0.495, 0.29, 0.368]}
          rotation={[Math.PI / 2, Math.PI / 4, 0]}
          scale={0.144}
        />
        <mesh
          name="Red006"
          castShadow
          receiveShadow
          geometry={nodes.Red006.geometry}
          material={materials["Material.026"]}
          position={[-0.72, 0.065, 0.368]}
          rotation={[Math.PI / 2, Math.PI / 4, 0]}
          scale={0.144}
        />
        <mesh
          name="Yellow006"
          castShadow
          receiveShadow
          geometry={nodes.Yellow006.geometry}
          material={materials["Material.024"]}
          position={[-0.494, -0.151, 0.368]}
          rotation={[Math.PI / 2, Math.PI / 4, 0]}
          scale={0.144}
        />
        <mesh
          name="Cylinder007"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder007.geometry}
          material={materials["Material.002"]}
          position={[-0.965, 0.89, 0.194]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.474, 0.104, 0.474]}
        />
        <mesh
          name="Lamp-cover007"
          castShadow
          receiveShadow
          geometry={nodes["Lamp-cover007"].geometry}
          material={materials["Material.001"]}
          position={[-0.965, 0.89, 0.165]}
          rotation={[Math.PI / 2, 0.192, 0]}
          scale={0.458}
        />
        <mesh
          name="screw_r007"
          castShadow
          receiveShadow
          geometry={nodes.screw_r007.geometry}
          material={materials.Material}
          position={[-0.565, 0.887, 0.449]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.038}
        />
        <mesh
          name="screw_l007"
          castShadow
          receiveShadow
          geometry={nodes.screw_l007.geometry}
          material={materials.Material}
          position={[-1.362, 0.887, 0.449]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.038}
        />
        <mesh
          name="Blue007"
          castShadow
          receiveShadow
          geometry={nodes.Blue007.geometry}
          material={materials["Material.030"]}
          position={[-0.74, 0.89, 0.368]}
          rotation={[Math.PI / 2, Math.PI / 4, 0]}
          scale={0.144}
        />
        <mesh
          name="Green007"
          castShadow
          receiveShadow
          geometry={nodes.Green007.geometry}
          material={materials["Material.028"]}
          position={[-0.961, 1.111, 0.368]}
          rotation={[Math.PI / 2, Math.PI / 4, 0]}
          scale={0.144}
        />
        <mesh
          name="Red007"
          castShadow
          receiveShadow
          geometry={nodes.Red007.geometry}
          material={materials["Material.027"]}
          position={[-1.186, 0.886, 0.368]}
          rotation={[Math.PI / 2, Math.PI / 4, 0]}
          scale={0.144}
        />
        <mesh
          name="Yellow007"
          castShadow
          receiveShadow
          geometry={nodes.Yellow007.geometry}
          material={materials["Material.029"]}
          position={[-0.959, 0.671, 0.368]}
          rotation={[Math.PI / 2, Math.PI / 4, 0]}
          scale={0.144}
        />
        <mesh
          name="Cylinder008"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder008.geometry}
          material={materials["Material.002"]}
          position={[-1.922, 0.89, 0.194]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.474, 0.104, 0.474]}
        />
        <mesh
          name="Lamp-cover008"
          castShadow
          receiveShadow
          geometry={nodes["Lamp-cover008"].geometry}
          material={materials["Material.001"]}
          position={[-1.922, 0.89, 0.165]}
          rotation={[Math.PI / 2, 0.192, 0]}
          scale={0.458}
        />
        <mesh
          name="screw_r008"
          castShadow
          receiveShadow
          geometry={nodes.screw_r008.geometry}
          material={materials.Material}
          position={[-1.52, 0.893, 0.449]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.038}
        />
        <mesh
          name="screw_l008"
          castShadow
          receiveShadow
          geometry={nodes.screw_l008.geometry}
          material={materials.Material}
          position={[-2.315, 0.882, 0.449]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.038}
        />
        <mesh
          name="Blue008"
          castShadow
          receiveShadow
          geometry={nodes.Blue008.geometry}
          material={materials["Material.031"]}
          position={[-1.714, 0.89, 0.368]}
          rotation={[Math.PI / 2, Math.PI / 4, 0]}
          scale={0.144}
        />
        <mesh
          name="Green008"
          castShadow
          receiveShadow
          geometry={nodes.Green008.geometry}
          material={materials["Material.033"]}
          position={[-1.935, 1.111, 0.368]}
          rotation={[Math.PI / 2, Math.PI / 4, 0]}
          scale={0.144}
        />
        <mesh
          name="Red008"
          castShadow
          receiveShadow
          geometry={nodes.Red008.geometry}
          material={materials["Material.034"]}
          position={[-2.16, 0.886, 0.368]}
          rotation={[Math.PI / 2, Math.PI / 4, 0]}
          scale={0.144}
        />
        <mesh
          name="Yellow008"
          castShadow
          receiveShadow
          geometry={nodes.Yellow008.geometry}
          material={materials["Material.032"]}
          position={[-1.933, 0.671, 0.368]}
          rotation={[Math.PI / 2, Math.PI / 4, 0]}
          scale={0.144}
        />
      </group>
    </group>
  );
}

// optional warm-cache, but guard it so it never runs in SSR:
if (typeof window !== "undefined") {
  useGLTF.preload("/models/Narokan_001.glb");
}

export default Narokan;
